name: "brise"
description: "Issue-[Issue Number] Branch Creator"
author: "ryosuke-horie"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ryosuke-horie/brise
        path: .github/actions/brise
    - uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: run main.go
      shell: bash
      run: cd .github/actions/brise && go run main.go
