name: sample

on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v2
          with:
            go-version: 1.23

        - name: run main.go
          run: go run main.go