name: sample

on:
  issues:
    types: [opened]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write      # リポジトリの内容を操作する権限
    issues: write        # イシューを作成・編集する権限
    pull-requests: write # 必要に応じてプルリクエストの権限も追加

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v2
          with:
            go-version: 1.23

        - name: check gh cli installed
          run: gh --version

        - name: run main.go
          run: go run main.go